site_name: Data Analysis
site_url: https://mickaeltemporao.github.io/data-analysis/

theme:
  font:
    text: Glory
    code: Source Code Pro
  langage: en
  name: material
  logo: "https://upload.wikimedia.org/wikipedia/commons/4/45/Glider.svg"
  favicon: images/favicon.ico
  palette:
    scheme: default
    primary: orange
    accent: red
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - footnotes
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mickaeltemporao
extra_css:
  - stylesheets/extra.css
  - css/custom.css
repo_url: https://github.com/mickaeltemporao/data-analysis

# Page tree
nav:
  - Home: index.md
  - syllabus.md
  - Activities:
    - activities/participation.md
    - activities/challenges.md
    - activities/project.md
  - Schedule:
    - schedule.md
    - Modules:
      - modules/introduction.md
      # - modules/tools.md
      # - modules/science.md
      - modules/variables.md
      - modules/data.md
      - modules/exploration-1.md
      - modules/exploration-2.md
      - modules/catch-up.md
      # - modules/next.md
      # - modules/wrangling.md
      # - modules/modeling.md
      # - modules/inference.md
      # - modules/explanation.md
      # - modules/communication.md
      # - modules/publication.md
      # - modules/management.md
      # - modules/descriptive-inference.md
      # - modules/causal-inference.md
      # - modules/programming-1.md
      # - modules/programming-2.md
      # - modules/programming-3.md
      # - modules/programming-4.md
      # - modules/exploration-1.md
      # - modules/exploration-2.md
      # - modules/exploration-3.md
      # - modules/exploration-4.md
      # - modules/exploration-5.md
      # - modules/management-1.md
      # - modules/sampling.md
      # - modules/measurement.md
      # - modules/replication.md
    # - Semestre 2:
      # - modules/programming.md
      # - modules/statistics.md
      # - modules/variables.md
      # - modules/hypothesis.md
      # - modules/analysis.md
      # - modules/communication.md
  - Resources:
    - resources/coding.md
    - resources/writing.md
    - resources/misc.md
    - resources/onboarding.md
  - Chat: "https://chat.whatsapp.com/Ie9P3jBaaHB2xPRJNztNRB"
  - This is Fine: "https://media.npr.org/assets/img/2023/01/14/this-is-fine_custom-b7c50c845a78f5d7716475a92016d52655ba3115.jpg"

validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn

copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><span property="dct:title">Data Analysis</span> by <span property="cc:attributionName">Mickael Tempor√£o</span> is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0</a></p>
